server:
  port: 80
spring:
  redis:
      database: 0 #redis数据库的索引，默认为0
      host: 192.168.20.8
  #    password:
      port: 6379
      pool:
        max-idle: 8 #最大空闲链接数
        min-idle: 0 #最小空闲连接数
        max-active: 8 #连接池最大连接数，负数表示无最大连接数
        max-wait: -1 #连接池最大阻塞等待时间，负数表示没有
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache-period: 0
    cache: false
  datasource:
    url: jdbc:mysql://123.56.12.124:3306/movie?characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    driver-path: C:\\Users\\cff\\.m2\\repository\\mysql\\mysql-connector-java\\5.1.40\\mysql-connector-java-5.1.40.jar
    hikari:
          maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
          maximumPoolSize: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
mybatis:
  typeAliasesPackage: com.movie.model
  mapperLocations: classpath*:mapper/**/*.xml
  configLocation: classpath:/mybatis-config.xml
#oss相关
endpoint: http://oss-cn-beijing.aliyuncs.com
accessKeyId: LTAIOymMDH5DQyY2
accessKeySecret: ER7SfUVjivxI6Tn3M5YQQAH6a02LBm
bucketName:
  video: foxmovie
  pic: foxmoviepic