server:
  port: 80
spring:
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache-period: 0
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/movie?characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    driver-path: C:\\Users\\cff\\.m2\\repository\\mysql\\mysql-connector-java\\5.1.40\\mysql-connector-java-5.1.40.jar
mybatis:
  typeAliasesPackage: com.movie.model
  mapperLocations: classpath*:mapper/**/*.xml
  configLocation: classpath:/mybatis-config.xml
#oss相关
endpoint: http://oss-cn-beijing.aliyuncs.com
accessKeyId: LTAIOymMDH5DQyY2
accessKeySecret: ER7SfUVjivxI6Tn3M5YQQAH6a02LBm
bucketName: foxmovie